In [27]:
import numpy as np
import pandas as pd
import math

In [15]:
# Create a Simple neural network


data = pd.DataFrame([[1,0,1],[0,1,1],[0,0,0],[1,1,1]],  columns = ['a','b','c'])


print(data)



   a  b  c
0  1  0  1
1  0  1  1
2  0  0  0
3  1  1  1


In [ ]:
# Initialize LearningRate 
epsilon = 0.01


In [41]:
# Initialze the Weights using Random function 

Layer1Weight1 = np.random.rand(2,1)
Layer1Weight2 = np.random.rand(2,1)
Layer1Weight3 = np.random.rand(2,1)

print("Layer1 Random weights")

print(Layer1Weight1)
print(Layer1Weight2)
print(Layer1Weight3)

print("Layer2 Random weights")

Layer2Weight1 = np.random.rand(1,1)
Layer2Weight2 = np.random.rand(1,1)
Layer2Weight3 = np.random.rand(1,1)

print(Layer2Weight1)
print(Layer2Weight2)
print(Layer2Weight3)


weights = {
    'layer1' : np.array([Layer1Weight1,Layer1Weight2,Layer1Weight3]),
    'layer2' : np.array([Layer2Weight1,Layer2Weight2,Layer2Weight3])
    
}


networkWeigts = pd.DataFrame([[np.random.rand(2,3)],[np.random.rand(3,1)]], index=['1','2'])


Layer1 Random weights
[[0.55187133]
 [0.67096884]]
[[0.12648359]
 [0.02862467]]
[[0.84507005]
 [0.16417906]]
Layer2 Random weights
[[0.2746712]]
[[0.25511521]]
[[0.8001665]]


In [26]:
# Initialize number of epochs  / Training cycles over dataset
epochs = 100


IMPLEMENTING THE FUNCTIONS

In [32]:
# sigmoid function
# 1 / (1+ e^(-X))
def sigmoid(X):
    return (1/(1+math.e**(-X)))



0.5


In [ ]:
# Forward propogate 
def (X,y, Weights):
    